### ISSUE TITLE
Support for arbitrary proxy directives

### ISSUE THREAD

**Issue by MrHash** [blacklabelops/nginx#13]
There are a [number of directives](http://nginx.org/en/docs/http/ngx_http_proxy_module.html) that would be useful to have configuration support for. For example for proxying socket connections a `proxy_read_timeout` is important. Other headers are offered as application specific support such as `proxy_http_version` at https://github.com/blacklabelops/nginx/blob/master/imagescripts/reverse_proxy.sh#L27.

Given the wide range of options would it not be a good idea to have some generic configuration support? I would suggest the pattern `SERVER1REVERSE_PROXY_HEADER1DIRECTIVE1=proxy_read_timeout 300` instead of requiring specific variables for each directive.

**Comment by blacklabelops** [comment]
Sure, why not.

**Comment by blacklabelops** [comment]
Implemented in development image: blacklabelops/nginx:development. Please check and give feedback!

Example:

~~~~
$ docker run -d \
    -p 80:80 \
    --name nginx \
    -e "SERVER1REVERSE_PROXY_LOCATION1=/" \
    -e "SERVER1REVERSE_PROXY_PASS1=http://www.heise.de" \
    -e "SERVER1REVERSE_PROXY_HEADER1DIRECTIVE1=proxy_read_timeout 300" \
    blacklabelops/nginx:development
~~~~

**Comment by MrHash** [comment]
Hey that's great. I happened to be doing an impl at the same time, but made a slight variation which you might like to consider: https://github.com/MrHash/nginx/commit/c30017203752c59b82cbdd6e75a4d7fa9f9f187d

**Comment by blacklabelops** [comment]
Ill take it! Especially because im too bored to do the documentation myself ;)

**Comment by blacklabelops** [comment]
Please do a pull request on the development branch.

**Comment by blacklabelops** [comment]
Finished, feature available in latest tag, versioned tag will come later.

**Comment by MrHash** [comment]
awesome! thanks
