### ISSUE TITLE
I18n characters in "uri", can we use "request_uri"?

### ISSUE THREAD

**Issue by v-gu** [blacklabelops/nginx#24]
Problem: as of current code base, the reverse proxy's pattern definition is:

```REVERSE_PROXY_BACKEND='$backend$uri$is_args$args'`

which Nginx will put normalized uri into "$uri". In normorlized mode, if there are I18n character in the uri, Nginx will sent out unescaped characters instead, which is not safe in some cases. For e.g., the newest version of tomcat prohibits unescaped characters in uri.

the "$request_uri" is an unescaped version of uri, if I edited the Nginx reverse proxy config manually and use "$request_uri" instead, tomcat will not complain again.

**Comment by blacklabelops** [comment]
Let's check this out.

**Comment by blacklabelops** [comment]
You can test the solution with image `blacklabelops/nginx:development`.

**Comment by v-gu** [comment]
Thank you @blacklabelops for the response time 👍 
But I suppose "$request_uri" contains "$is_args$args" already?

I suppose `REVERSE_PROXY_BACKEND='$backend$request_uri'`  is enough?

Thx!

**Comment by blacklabelops** [comment]
I don't know. Regarding this issue i'm dependent on your expert knowledge :)

**Comment by v-gu** [comment]
`REVERSE_PROXY_BACKEND='$backend$request_uri` will be just fine. 

thank you~

**Comment by blacklabelops** [comment]
Works for me, please recheck the latest `blacklabelops/nginx:development`.

**Comment by v-gu** [comment]
Works for me 2.
