### ISSUE TITLE
reverse proxy to vhost: accesses backend as IP address instead of domain name

### ISSUE THREAD

**Issue by wivaku** [blacklabelops/nginx#27]
Using reverse proxy to vhost. It seems to access the backend site as IP address instead of domain name. As a result the backend server (potentially) returns the incorrect site.

E.g.: I set up a reverse proxy that forwards to domain2.com.
domain1.com and domain2.com both point to 12.34.56.78
The reverse proxy request is sent to 12.34.56.78 instead of domain2.com, which then serves the default content for 12.34.56.78 instead of domain2.com.

**Comment by blacklabelops** [comment]
Yes, this image is build that nginx resolves the ip address for each domain using docker's internal dns resolver. If your container gets a new ip address assigned the container will be unreachable, this can be the case after each container restart.

**Comment by wivaku** [comment]
Not sure if I understand (keep in mind all this is relatively new to me!). I thought when using a [Docker network](https://docs.docker.com/compose/networking/) it will resolve ok? 

```
bash-4.3# ping -c1 www.github.com
PING www.github.com (192.30.253.112): 56 data bytes
64 bytes from 192.30.253.112: seq=0 ttl=51 time=87.413 ms
--- www.github.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 87.413/87.413/87.413 ms

bash-4.3# ping -c1 jiracore
PING jiracore (172.18.0.7): 56 data bytes
64 bytes from 172.18.0.7: seq=0 ttl=64 time=0.082 ms
--- jiracore ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.082/0.082/0.082 ms
```

**Comment by blacklabelops** [comment]
Example:

1. Create Docker Network
1. Start Nginx Container on Docker Network
1. Start Jira Container on Docker Network
1. Remove Jira Container on Docker Network
1. Start New Jira Container on Docker Network

=> Jira will get new IP. (Or high probabilty that Jira will get new Ip)

Nginx by default will stick to one ip! You will have to restart Nginx to get the thing going again!

**Comment by wivaku** [comment]
Yes, the IP address of a container can change, just like the IP address of external system. Nginx will not notice this?

**Comment by blacklabelops** [comment]
I am using the following configuration line for this:
resolver 127.0.0.11  ipv6=off valid=30s;
