### ISSUE TITLE
set client_max_body_size to 10M

### ISSUE THREAD

**Issue by wivaku** [blacklabelops/nginx#29]
The [Jira documentation](https://confluence.atlassian.com/jirakb/integrating-jira-with-nginx-426115340.html) suggests setting `client_max_body_size` to 10M

> By default Nginx allows 1MB file to be attached into JIRA. So, parameter client_max_body_size is necessary to set the maximum size of attachment that can be uploaded into JIRA

Did not see it in the location or server context in the nginx container.

**Comment by blacklabelops** [comment]
This is servers default:
client_max_body_size  100m;

**Comment by wivaku** [comment]
great, thanks for checking!
