### ISSUE TITLE
hook mechanism to put proxy specific files

### ISSUE THREAD

**Issue by wivaku** [blacklabelops/nginx#30]
Related to https://github.com/blacklabelops/nginx/issues/27

I want to achieve:

- use env to specify the Jira configurations
- add additional locations (this because these locations are vhost servers, and the default env way of configuring locations use an internal resolver, and will access the upstream server by IP address)

I now do this manually, based on the [nginx documentation](https://www.nginx.com/resources/admin-guide/reverse-proxy/):

- bring up the nginx container
- copy (e.g.) additionalLocations.conf to /etc/nginx/conf.d/server1/
- nginx -s reload

```
bash-4.3# ls -l /etc/nginx/conf.d/server1
total 8
-rw-r--r--    1 root     root           148 Jun  6 12:15 additionalLocations.conf
-rw-r--r--    1 root     root          1961 Jun  6 12:14 reverseProxy.conf
```

```
bash-4.3# cat /etc/nginx/conf.d/server1/additionalLocations.conf
location /external_site/ {
  proxy_pass http://www.myvhostdomain.com/;
}
```

Would be great if I can a) specify the additionalLocations.conf in my docker-compose config, and/or b) use env setting to specify I want to use the "pass-through" simple format, instead of the default one.

**Comment by blacklabelops** [comment]
You can now hook a proxy configuration with:

~~~~
docker run -d     
  -p 80:80     
  --name nginx     
  -e "SERVER1PROXY_CONFIGURATION=/mydat.conf"      
  blacklabelops/nginx
~~~~

Must be a valid nginx proxy configuration:

~~~~
location / {
          set $backend "http://www.thedesiredlocation.com";
          proxy_pass $backend$request_uri;
          proxy_set_header X_FORWARDED_PROTO $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Server $host;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header Host $host;
          port_in_redirect off;
 }
~~~~

**Comment by wivaku** [comment]
very useful, thanks! Can I use it in these two cases?
- **only custom config**: no need for _PROXY_LOCATION and _PROXY_PASS1
- **both default behavior and custom config**: use both _CONFIGURATION and _PROXY_LOCATION + _PROXY_PASS1

E.g. only custom config:

      SERVER3SERVER_NAME: ${TOOL_DOMAIN_NAME}
      # SERVER3REVERSE_PROXY_LOCATION1: "/"
      # SERVER3REVERSE_PROXY_PASS1: ${TOOL_URL_PASS}
      SERVER3PROXY_CONFIGURATION: ${NGINX_CUSTOM_TOOL}

Will test later this week.

**Comment by blacklabelops** [comment]
You can only use PROXY_CONFIGURATION or REVERSE_PROXY_LOCATION with REVERSE_PROXY_PASS. Both will result in an error.

**Comment by wivaku** [comment]
This works Steffen!
I did have to add a mount:
```
volumes:
- ./my_config_folder:/nginx_custom_config
environment:
  SERVER3SERVER_NAME: ${TOOL_DOMAIN_NAME}
  SERVER3PROXY_CONFIGURATION: /nginx_custom_config/SERVER3.conf
```

**Comment by blacklabelops** [comment]
Thank you for testing!
