### ISSUE TITLE
ip not forwarded

### ISSUE THREAD

**Issue by eOperationsPN** [blacklabelops/nginx#35]
Hi

in `docker logs -f blacklabelops/nginx` for every request `172.25.0.1` is displayed. seems that client ips are not forwarded. do i miss something out?

thanks

**Comment by blacklabelops** [comment]
Sorry, I do not understand what you try to accomplish. Also it sounds rather like a nginx question than some issues with this Docker image.

**Comment by eOperationsPN** [comment]
Yes you are completely right. Its not an issue with this image. thanks anyway.
